default: &DEFAULT
  batch_size: 100
  test_set_size: 0.1
  labels: [
    'normal',
    'auti'
  ] #speacify labels to draw
  cell: sru  # simplified recursion unit
  init_state_type: var
  dilation: [1, 2, 4, 8, 16, 32]
  num_hidden: 128
  metric: cosine
  num_epoch: 1000
  optimizer: rmsp
  learning_rate: 1.0e-4
  decay_rate: 0.97
  test_interval: 1
  loss: logisitc

large_hidden:
  <<: *DEFAULT
  num_hidden: 1024